### ISSUE TITLE
Feature request: Preserve case of HTTP header names

### ISSUE THREAD

**Issue by landsman** [JarvusInnovations/node-request-to-curl#2]
great package - thanks!

I have only one problem - my headers are automatically converted to lowercase but on input is uppercase. It can be problem for repeating if server is case-sensitive.

**Comment by jmealo** [comment]
@landsman: this was/is the behavior of node’s http-parser, I’ll have to check if the pure javascript http-parser we use now has an option to preserve case.

**Comment by jmealo** [comment]
@landsman: The spec states that the HTTP header names should be case-insensitive. Since you're here, using this module, I can only suppose that you might be interacting with a misbehaving server that you don't have control over. To help people in such a situation, I can see where this is a valuable feature, even though it's out-of-spec.

**Comment by landsman** [comment]
Yes, you are right. I fixed backend to case-insensitive.
